// Generated by gencpp from file control/MoveJointsResponse.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_MOVEJOINTSRESPONSE_H
#define CONTROL_MESSAGE_MOVEJOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace control
{
template <class ContainerAllocator>
struct MoveJointsResponse_
{
  typedef MoveJointsResponse_<ContainerAllocator> Type;

  MoveJointsResponse_()
    : current()  {
    }
  MoveJointsResponse_(const ContainerAllocator& _alloc)
    : current(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _current_type;
  _current_type current;





  typedef boost::shared_ptr< ::control::MoveJointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control::MoveJointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveJointsResponse_

typedef ::control::MoveJointsResponse_<std::allocator<void> > MoveJointsResponse;

typedef boost::shared_ptr< ::control::MoveJointsResponse > MoveJointsResponsePtr;
typedef boost::shared_ptr< ::control::MoveJointsResponse const> MoveJointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control::MoveJointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control::MoveJointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control::MoveJointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::MoveJointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::MoveJointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::MoveJointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::MoveJointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::MoveJointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control::MoveJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5fdd6623403b3efdfab2ff5de8c8453";
  }

  static const char* value(const ::control::MoveJointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5fdd6623403b3efULL;
  static const uint64_t static_value2 = 0xdfab2ff5de8c8453ULL;
};

template<class ContainerAllocator>
struct DataType< ::control::MoveJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control/MoveJointsResponse";
  }

  static const char* value(const ::control::MoveJointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control::MoveJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Twist current\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::control::MoveJointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control::MoveJointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveJointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control::MoveJointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control::MoveJointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MESSAGE_MOVEJOINTSRESPONSE_H
