station_count: 5

train_name: I C E 6 8 0

station_1:
  Name: Munich
  Time: 9-00
  Date: 07.02.2023

station_2:
  Name: Ingolstadt
  Time: 9-45
  Date: 07.02.2023

station_3:
  Name: Fulda
  Time: 11-45
  Date: 07.02.2023

station_4:
  Name: Hannover
  Time: 13-15
  Date: 07.02.2023

station_5:
  Name: Hamburg
  Time: 15-00
  Date: 07.02.2023

ticket_count: 5

ticket_1:
  ID: NAO2301
  Name: Jack
  Date: 07.02.2023
  From: Munich
  DepartureTime: 9-00
  To: Hannover
  ArrivalTime: 13-15
  Train: I C E 6 8 0

ticket_2:
  ID: NAO2302
  Name: Mike
  Date: 07.02.2023
  From: Ingolstadt
  DepartureTime: 9-00
  To: Hamburg
  ArrivalTime: 15-00
  Train: I C E 6 8 0

ticket_3:
  ID: NAO2303
  Name: Amy
  Date: 07.02.2023
  From: Fulda
  DepartureTime: 9-00
  To: Hamburg
  ArrivalTime: 15-00
  Train: I C E 6 8 0

ticket_4:
  ID: NAO2304
  Name: Tom
  Date: 07.02.2023
  From: Fulda
  DepartureTime: 13-15
  To: Hamburg
  ArrivalTime: 15-00
  Train: I C E 6 8 0

ticket_5:
  ID: NAO2305
  Name: John
  Date: 07.02.2023
  From: Hannover
  DepartureTime: 13-15
  To: Hamburg
  ArrivalTime: 15-00
  Train: I C E 6 8 0

passenger_count: 5

passenger_1:
  ID: 0
  Name: Jack
  Gender: Male

passenger_2:
  ID: 1
  Name: Mike
  Gender: Male

passenger_3:
  ID: 2
  Name: Amy
  Gender: Female

passenger_4:
  ID: 3
  Name: Tom
  Gender: Male

passenger_5:
  ID: 4
  Name: John
  Gender: Male
