#CREATE request parameters
int8 task
string name

float32 mask
geometry_msgs/Twist target

float32 max_speed
float32 time
--------------------------------
#CREATE response parameters
geometry_msgs/Twist current